name: Build gem

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby

      - name: Build gem
        run: gem build sonic-pi-cli.gemspec

      - uses: actions/upload-artifact@v7
        with:
          name: sonic-pi-cli-gem
          path: "*.gem"
          if-no-files-found: error
